volumes:
  modules:

services:
  www:
    image: kevinnls/node-unprivileged:alpine
    container_name: learning-www-vite
    user: node
    volumes:
      - ./:/app
      - modules:/app/node_modules
    ports:
      - ${PORT:-8080}:80
